### ISSUE TITLE
Object in plugin error

### ISSUE THREAD

**Issue by brian-a-moore** [react-native-google-signin/docs#13]
I’m getting an error following the google signin instructions for expo where the iOS url scheme is in an object in the plugins section of app.json. When I follow these instructions, my app does not compile and I get typescript errors stating the plugins array should only contain strings.

**Comment by vonovak** [comment]
Hello and thanks for reporting,
it'd help to know:

- what your app.json looks like
- what build error you get
- what TS error you get and where


Thank you 🙂
