### ISSUE TITLE
Setup guide references a version that doesn't exist

### ISSUE THREAD

**Issue by bob-devereux** [react-native-google-signin/docs#6]
The [setup guide](https://github.com/react-native-google-signin/docs/blob/main/docs/setting-up/android.md) seems to be saying you may need to install "12.1.0" of react-native-google-signin which doesn't seem to exist.  Am I misreading the documentation?

**Comment by vonovak** [comment]
Hello and thanks for asking,
that section starts with "If you're using the sponsor package". So it's only related to the sponsor-only package, which follows different versioning (currently it's version 14.2.)
Thank you 🙂
